### ISSUE TITLE
Compatibility with IOS apps 2.0.x

### ISSUE THREAD

**Issue by ipa64** [kayno/arduinolifx#1]
Hi, at first thanks for your job, I use arduino bulb since few month now. But just after the last update of iOS apps 2.0.x I can not see my arduino bulb anymore ( it's still working with other apps).
Do you know something about that?
Kind regards 
Patrick

**Comment by kayno** [comment]
Hi Patrick

I've noticed the same - v2 app (android) does not see the arduino bulb. I have captured some network traffic to try and see what is happening, and will let you know if I find a solution.

Cheers
Kayne

**Comment by ipa64** [comment]
Thanks, I hope you will find a solution.

I have add IR receiver to the code source, so you can use arduino bulb even without a smartphone just with a standard IR remote for strip led.

Cheers
Patrick

**Comment by kayno** [comment]
Hi Patrick

I've just pushed some changes to resolve this. I can control the arduino bulb with the Android v2 LIFX app - could you try now with the iOS app?

Thanks
Kayne

**Comment by ipa64** [comment]
Hi Kayne,
YES it's working with IOS apps too.
Thanks a lot.
Patrick
