### ISSUE TITLE
Not working with latest Lifx update 2.3,x

### ISSUE THREAD

**Issue by ipa64** [kayno/arduinolifx#2]
Hi Kayno,
Are you still working on this project?
I like it, I use it for a while now (I don't' understand why lifx doesn't provide an strip driver compliant).
But now they are using a cloud to access bulb from anywhere, and Lifx apps Widget companion too, so it's not compliant with arduinolifx anymore.
Can I hope you could spend time to update your project?

King regards

**Comment by kalopilato** [comment]
I'd love to know about this too!

**Comment by ipa64** [comment]
I've just made one from an electronic board got in a lifx bulb! 
http://youtu.be/BRIm3nd8kqc

**Comment by kayno** [comment]
I'm using the LIFX 2.3.4 app, and I'm able to control an arduinolifx still. It comes up down the bottom of the lights list under the group "Update needed", and you can select it there. You can't update it though, nor can you add it to the LIFX cloud.

If I can find some time I will have a look at capturing some packets for a lifx v2 firmware bulb and see if arduinolifx can be updated to match.

@ipa64 - what you have done is awesome!! Can you share your circuit please??

**Comment by ipa64** [comment]
Yes of course!
For the primary power supply I use an 7.5V 500mA
I bought the led amplifier and LED strip on Alibabaexpress.
![image](https://cloud.githubusercontent.com/assets/10351617/9699984/61474f6a-53f4-11e5-867c-4af5d5c6052b.jpg)

**Comment by ipa64** [comment]
![image](https://cloud.githubusercontent.com/assets/10351617/9700767/3a2af2c6-5410-11e5-8b60-8b01ccfa64fb.jpg)

**Comment by ipa64** [comment]
I have just printed a box to fit it
![image](https://cloud.githubusercontent.com/assets/10351617/9703574/d7664d42-5488-11e5-9440-d31a6ca45921.jpg)
![image](https://cloud.githubusercontent.com/assets/10351617/9703575/d7868f8a-5488-11e5-8765-8fa6df0189a0.jpg)
